#!/usr/bin/env bash
set -euo pipefail

export WANDB_API_KEY="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"
export WANDB_MODE="online"
export WANDB_PROJECT="icml_long"

STUDENT_MODEL="${STUDENT_MODEL:-Qwen/Qwen3-0.6B-Base}"
TEACHER_MODEL="${TEACHER_MODEL:-Qwen/Qwen3-4B}"
TRAIN_FILE="${TRAIN_FILE:?Set TRAIN_FILE to the prepared guanning-ai/dapo14k parquet}"
VAL_FILES="${VAL_FILES:-['$TRAIN_FILE']}"
N_GPUS="${N_GPUS:-8}"
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-128}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-1024}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-2048}"
OUTPUT_DIR="${OUTPUT_DIR:-/G-OPD-checkpoints/Qwen3-0.6B-Base-Vanilla-OPD}"
SAVE_FREQ="${SAVE_FREQ:-50}"
MAX_ACTOR_CKPTS="${MAX_ACTOR_CKPTS:-2}"
ENABLE_GRADIENT_CHECKPOINTING="${ENABLE_GRADIENT_CHECKPOINTING:-true}"
ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU="${ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU:-4}"
ROLLOUT_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${ROLLOUT_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-4}"
REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-4}"
VLLM_GPU_MEMORY_UTILIZATION="${VLLM_GPU_MEMORY_UTILIZATION:-0.6}"

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    algorithm.use_kl_in_reward=false \
    data.train_files="$TRAIN_FILE" \
    data.val_files="$VAL_FILES" \
    data.train_batch_size="$TRAIN_BATCH_SIZE" \
    data.max_prompt_length="$MAX_PROMPT_LENGTH" \
    data.max_response_length="$MAX_RESPONSE_LENGTH" \
    data.filter_overlong_prompts=true \
    data.truncation=error \
    data.shuffle=true \
    data.seed=42 \
    data.return_raw_chat=true \
    +data.apply_chat_template_kwargs.enable_thinking=false \
    actor_rollout_ref.model.path="$STUDENT_MODEL" \
    +actor_rollout_ref.ref.model.path="$TEACHER_MODEL" \
    actor_rollout_ref.model.use_remove_padding=true \
    actor_rollout_ref.model.enable_gradient_checkpointing="$ENABLE_GRADIENT_CHECKPOINTING" \
    actor_rollout_ref.actor.optim.lr=1e-5 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.0 \
    actor_rollout_ref.actor.policy_loss.only_reverse_kl_advantages=true \
    actor_rollout_ref.actor.policy_loss.lambda_vals=1.0 \
    actor_rollout_ref.actor.policy_loss.multi_teacher_distill=false \
    actor_rollout_ref.actor.policy_loss.slqp.enabled=false \
    actor_rollout_ref.actor.ppo_mini_batch_size="$TRAIN_BATCH_SIZE" \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu="$ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU" \
    actor_rollout_ref.actor.ppo_epochs=1 \
    actor_rollout_ref.actor.shuffle=false \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.use_kl_loss=true \
    actor_rollout_ref.actor.kl_loss_coef=0 \
    actor_rollout_ref.actor.fsdp_config.param_offload=false \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=false \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.n=1 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu="$ROLLOUT_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU" \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization="$VLLM_GPU_MEMORY_UTILIZATION" \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.top_p=1.0 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu="$REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU" \
    actor_rollout_ref.ref.fsdp_config.param_offload=false \
    reward_model.reward_manager=naive \
    trainer.critic_warmup=0 \
    trainer.val_before_train=false \
    trainer.logger='["console","wandb"]' \
    trainer.project_name=icml_long \
    trainer.experiment_name=qwen3-0.6b-base-to-qwen3-4b \
    trainer.n_gpus_per_node="$N_GPUS" \
    trainer.nnodes=1 \
    trainer.default_local_dir="$OUTPUT_DIR" \
    trainer.save_freq="$SAVE_FREQ" \
    trainer.max_actor_ckpt_to_keep="$MAX_ACTOR_CKPTS" \
    trainer.max_critic_ckpt_to_keep=1 \
    trainer.test_freq=-1 \
    trainer.total_epochs=1 \
    "$@"
